[package]
name = "rustq"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0"
hwfq = { path="/users/mahailem/hwfq", features = ["htb-argparse", "drr-argparse"] }
tracing-subscriber = "0.3"
tracing = "0.1"
